//! Layer 3: Policy Engine.
//!
//! Provides intent-based automatic model selection. Task tags are matched
//! to routing rules, which select a policy that determines the optimal model
//! based on constraints (cost, latency, quality) and preferences.

pub mod config;
pub mod scoring;

use std::time::Duration;

use serde::Serialize;

use crate::Result;
use crate::error::HamoruError;
use crate::provider::ModelInfo;
use crate::telemetry::MetricsCache;

pub use config::{
    CostLimits, DefaultPolicy, MatchRule, PolicyConfig, PolicyConstraints, PolicyDefinition,
    PolicyPreferences, Priority, QualityTier, RoutingRule,
};

/// Intent-based model selection engine.
///
/// Routes requests to the optimal model based on tags, policies, and constraints.
/// Synchronous — no async methods, no I/O. Operates on cached metrics data.
pub trait PolicyEngine: Send + Sync {
    /// Selects the optimal model for a request based on tags and policy rules.
    ///
    /// Flow: match tags → routing_rules → identify policy → filter by capabilities
    /// → narrow by constraints → score by preferences → return optimal model.
    fn select_model(
        &self,
        request: &RoutingRequest,
        available_models: &[ModelInfo],
        metrics_cache: &MetricsCache,
    ) -> Result<ModelSelection>;

    /// Selects a fallback model after the primary selection fails.
    ///
    /// Excludes the original model and re-runs selection with the same policy.
    /// Returns `Ok(None)` if no alternative model is available.
    fn select_fallback_model(
        &self,
        original: &ModelSelection,
        error: &HamoruError,
        available_models: &[ModelInfo],
    ) -> Result<Option<ModelSelection>>;

    /// Checks whether an estimated cost exceeds any configured limits.
    ///
    /// Returns a `CostCheckResult` indicating whether the request is allowed,
    /// which limit was exceeded (if any), and whether an alert threshold was hit.
    fn check_cost_limits(
        &self,
        estimated_cost: f64,
        metrics_cache: &MetricsCache,
    ) -> Result<CostCheckResult>;

    /// Simulates the cost impact of a policy configuration change.
    ///
    /// Used by `hamoru plan` to predict cost changes before applying.
    fn simulate_cost_impact(
        &self,
        current_config: &PolicyConfig,
        proposed_config: &PolicyConfig,
        metrics_cache: &MetricsCache,
    ) -> Result<CostImpactReport>;
}

/// A request to be routed to a model via policy rules.
#[derive(Debug, Clone, Default, Serialize)]
pub struct RoutingRequest {
    /// Tags describing the task intent (e.g., `["review", "security"]`).
    pub tags: Vec<String>,
    /// Explicit policy name override (from `-p` flag).
    pub policy_name: Option<String>,
    /// Estimated input tokens for cost prediction.
    pub estimated_input_tokens: Option<u64>,
    /// Estimated output tokens for cost prediction.
    pub estimated_output_tokens: Option<u64>,
}

/// The result of model selection — which model to use and why.
#[derive(Debug, Clone, Serialize)]
pub struct ModelSelection {
    /// Provider identifier (e.g., "claude", "ollama").
    pub provider: String,
    /// Model identifier (e.g., "claude-sonnet-4-6").
    pub model: String,
    /// Name of the policy that was applied.
    pub policy_applied: String,
    /// Human-readable explanation of why this model was selected.
    pub reason: String,
    /// Estimated cost for this request in USD.
    pub estimated_cost: Option<f64>,
    /// Final score from the scoring algorithm.
    pub score: f64,
}

/// Result of a cost limit check.
#[derive(Debug, Clone, Default, Serialize)]
pub struct CostCheckResult {
    /// Whether the request is allowed within limits.
    pub allowed: bool,
    /// Which limit was exceeded (e.g., "per_day"), if any.
    pub limit_exceeded: Option<String>,
    /// Current accumulated spend in the exceeded category.
    pub current_spend: f64,
    /// Maximum allowed spend for the exceeded category.
    pub max_allowed: f64,
    /// Whether the alert threshold was crossed (spend near limit).
    pub alert: bool,
    /// Human-readable alert message, if alert is true.
    pub alert_message: Option<String>,
}

/// Serializes a `Duration` as its whole seconds count (u64).
fn serialize_duration_secs<S: serde::Serializer>(
    d: &Duration,
    s: S,
) -> std::result::Result<S::Ok, S::Error> {
    s.serialize_u64(d.as_secs())
}

/// Predicted cost impact of a policy change.
///
/// Generated by `simulate_cost_impact` for `hamoru plan`.
#[derive(Debug, Clone, Serialize)]
pub struct CostImpactReport {
    /// Estimated daily cost change in USD.
    pub estimated_daily_change: f64,
    /// Which models traffic shifts from/to.
    pub model_shift: Vec<ModelShift>,
    /// Prediction confidence (based on telemetry data volume).
    pub confidence: f64,
    /// Telemetry period used for the prediction.
    #[serde(serialize_with = "serialize_duration_secs")]
    pub period_used: Duration,
}

/// A predicted shift in model usage from a policy change.
#[derive(Debug, Clone, Serialize)]
pub struct ModelShift {
    /// Model losing traffic.
    pub from_model: String,
    /// Model gaining traffic.
    pub to_model: String,
    /// Estimated percentage of traffic shifting.
    pub estimated_percentage: f64,
    /// Cost delta in USD (positive = more expensive).
    pub cost_delta: f64,
}

/// Shared test fixtures for policy module tests.
///
/// Provides common `ModelInfo` and `MetricsCache` builders used across
/// `scoring`, `engine`, and other policy submodule tests.
#[cfg(test)]
pub(crate) mod test_fixtures {
    use std::collections::HashMap;

    use crate::provider::{Capability, ModelInfo};
    use crate::telemetry::{MetricsCache, ModelMetrics};

    /// Claude Sonnet-class model (High tier).
    pub(crate) fn model_sonnet() -> ModelInfo {
        ModelInfo {
            id: "claude-sonnet-4-6".to_string(),
            provider: "claude".to_string(),
            context_window: 200_000,
            cost_per_input_token: 3.0 / 1_000_000.0,
            cost_per_output_token: 15.0 / 1_000_000.0,
            cost_per_cached_input_token: Some(0.3 / 1_000_000.0),
            capabilities: vec![
                Capability::Chat,
                Capability::Vision,
                Capability::FunctionCalling,
            ],
            max_output_tokens: Some(64_000),
        }
    }

    /// Claude Haiku-class model (Medium tier).
    pub(crate) fn model_haiku() -> ModelInfo {
        ModelInfo {
            id: "claude-haiku-4-5".to_string(),
            provider: "claude".to_string(),
            context_window: 200_000,
            cost_per_input_token: 0.8 / 1_000_000.0,
            cost_per_output_token: 4.0 / 1_000_000.0,
            cost_per_cached_input_token: Some(0.08 / 1_000_000.0),
            capabilities: vec![Capability::Chat, Capability::FunctionCalling],
            max_output_tokens: Some(64_000),
        }
    }

    /// Local Llama model (Low tier, free).
    pub(crate) fn model_llama_70b() -> ModelInfo {
        ModelInfo {
            id: "llama3.3:70b".to_string(),
            provider: "ollama".to_string(),
            context_window: 128_000,
            cost_per_input_token: 0.0,
            cost_per_output_token: 0.0,
            cost_per_cached_input_token: None,
            capabilities: vec![Capability::Chat],
            max_output_tokens: None,
        }
    }

    /// Creates a `ModelInfo` with custom cost values.
    pub(crate) fn model_with_cost(
        id: &str,
        provider: &str,
        input: f64,
        output: f64,
    ) -> ModelInfo {
        ModelInfo {
            id: id.to_string(),
            provider: provider.to_string(),
            context_window: 128_000,
            cost_per_input_token: input,
            cost_per_output_token: output,
            cost_per_cached_input_token: None,
            capabilities: vec![Capability::Chat],
            max_output_tokens: None,
        }
    }

    /// Creates a `ModelInfo` with specified capabilities.
    pub(crate) fn model_with_capabilities(
        id: &str,
        provider: &str,
        caps: Vec<Capability>,
    ) -> ModelInfo {
        ModelInfo {
            id: id.to_string(),
            provider: provider.to_string(),
            context_window: 128_000,
            cost_per_input_token: 1.0 / 1_000_000.0,
            cost_per_output_token: 5.0 / 1_000_000.0,
            cost_per_cached_input_token: None,
            capabilities: caps,
            max_output_tokens: None,
        }
    }

    /// Returns an empty `MetricsCache` (zero data).
    pub(crate) fn empty_metrics_cache() -> MetricsCache {
        MetricsCache::default()
    }

    /// Builds a `MetricsCache` with per-model latency entries.
    ///
    /// Each entry is `(model_id, avg_latency_ms)`.
    pub(crate) fn metrics_cache_with_latency(
        entries: &[(&str, f64)],
    ) -> MetricsCache {
        let mut by_model = HashMap::new();
        for &(model_id, latency) in entries {
            by_model.insert(
                model_id.to_string(),
                ModelMetrics {
                    provider: String::new(),
                    requests: 10,
                    cost: 0.0,
                    input_tokens: 0,
                    output_tokens: 0,
                    avg_latency_ms: latency,
                },
            );
        }
        MetricsCache {
            by_model,
            period_days: 7,
            entry_count: entries.len() as u64 * 10,
            ..Default::default()
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn routing_request_default() {
        let req = RoutingRequest::default();
        assert!(req.tags.is_empty());
        assert!(req.policy_name.is_none());
        assert!(req.estimated_input_tokens.is_none());
        assert!(req.estimated_output_tokens.is_none());
    }

    #[test]
    fn cost_check_result_default() {
        let result = CostCheckResult::default();
        assert!(!result.allowed);
        assert!(result.limit_exceeded.is_none());
        assert!(!result.alert);
        assert!(result.alert_message.is_none());
    }

    #[test]
    fn cost_impact_report_serializes() {
        let report = CostImpactReport {
            estimated_daily_change: 0.16,
            model_shift: vec![ModelShift {
                from_model: "llama3.3:70b".to_string(),
                to_model: "claude-sonnet-4-6".to_string(),
                estimated_percentage: 12.0,
                cost_delta: 0.013,
            }],
            confidence: 0.82,
            period_used: Duration::from_secs(7 * 86400),
        };
        let json = serde_json::to_string(&report).unwrap();
        assert!(json.contains("\"estimated_daily_change\":0.16"));
        // Duration serialized as seconds
        assert!(json.contains("\"period_used\":604800"));
    }

    #[test]
    fn model_shift_serializes() {
        let shift = ModelShift {
            from_model: "a".to_string(),
            to_model: "b".to_string(),
            estimated_percentage: 50.0,
            cost_delta: -0.01,
        };
        let json = serde_json::to_string(&shift).unwrap();
        assert!(json.contains("\"from_model\":\"a\""));
        assert!(json.contains("\"cost_delta\":-0.01"));
    }
}
