//! Layer 3: Policy Engine.
//!
//! Provides intent-based automatic model selection. Task tags are matched
//! to routing rules, which select a policy that determines the optimal model
//! based on constraints (cost, latency, quality) and preferences.

use std::time::Duration;

use crate::Result;
use crate::error::HamoruError;
use crate::provider::LlmProvider;
use crate::telemetry::MetricsCache;

/// Intent-based model selection engine.
///
/// Routes requests to the optimal model based on tags, policies, and constraints.
/// Synchronous — no async methods, no I/O. Operates on cached metrics data.
pub trait PolicyEngine: Send + Sync {
    /// Selects the optimal model for a request based on tags and policy rules.
    ///
    /// Flow: match tags → routing_rules → identify policy → filter by capabilities
    /// → narrow by constraints → score by preferences → return optimal model.
    fn select_model(
        &self,
        request: &RoutingRequest,
        available_providers: &[&dyn LlmProvider],
        metrics_cache: &MetricsCache,
    ) -> Result<ModelSelection>;

    /// Selects a fallback model after the primary selection fails.
    fn select_fallback_model(
        &self,
        original: &ModelSelection,
        error: &HamoruError,
        available_providers: &[&dyn LlmProvider],
    ) -> Result<Option<ModelSelection>>;

    /// Checks whether an estimated cost exceeds any configured limits.
    fn check_cost_limits(
        &self,
        estimated_cost: f64,
        metrics_cache: &MetricsCache,
    ) -> Result<CostCheckResult>;

    /// Simulates the cost impact of a policy configuration change.
    ///
    /// Used by `hamoru plan` to predict cost changes before applying.
    fn simulate_cost_impact(
        &self,
        current_config: &PolicyConfig,
        proposed_config: &PolicyConfig,
        metrics_cache: &MetricsCache,
    ) -> Result<CostImpactReport>;
}

/// A request to be routed to a model via policy rules.
// TODO: Finalize fields in Phase 3.
#[derive(Debug, Clone, Default)]
pub struct RoutingRequest;

/// The result of model selection — which model to use and why.
// TODO: Finalize fields in Phase 3.
#[derive(Debug, Clone, Default)]
pub struct ModelSelection;

/// Result of a cost limit check.
// TODO: Finalize fields in Phase 3.
#[derive(Debug, Clone, Default)]
pub struct CostCheckResult;

/// Policy configuration (parsed from YAML).
// TODO: Finalize fields in Phase 3.
#[derive(Debug, Clone, Default)]
pub struct PolicyConfig;

/// Predicted cost impact of a policy change.
///
/// Generated by `simulate_cost_impact` for `hamoru plan`.
#[derive(Debug, Clone)]
pub struct CostImpactReport {
    /// Estimated daily cost change in USD.
    pub estimated_daily_change: f64,
    /// Which models traffic shifts from/to.
    pub model_shift: Vec<ModelShift>,
    /// Prediction confidence (based on telemetry data volume).
    pub confidence: f64,
    /// Telemetry period used for the prediction.
    pub period_used: Duration,
}

/// A predicted shift in model usage from a policy change.
#[derive(Debug, Clone)]
pub struct ModelShift {
    /// Model losing traffic.
    pub from_model: String,
    /// Model gaining traffic.
    pub to_model: String,
    /// Estimated percentage of traffic shifting.
    pub estimated_percentage: f64,
    /// Cost delta in USD (positive = more expensive).
    pub cost_delta: f64,
}
